variable "rg_name" {}
variable "location" {}
variable "managed_by" {}
variable "vnet_name" {}
variable "vnet_address_space" {}
variable "subnet_name" {}
variable "subnet_address_prefixes" {}
variable "public_ip_name" {}
variable "public_ip_allocation_method" {}
variable "public_ip_sku" {}
variable "bastion_host_name" {}
variable "ip_congiguration_name" {}