name: Stage Terraform Validation

on:
  push:
    branches:
      - stage

  pull_request:
    branches:
      - stage

permissions:
  contents: read
  security-events: write

env:
  TF_WORKING_DIR: ./Terraform-Modules/Non-Production
  TF_VERSION: 1.13.2

jobs:
  terraform-validation:

    name: Terraform Validation and Security Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          tflint --init
          tflint --recursive

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ env.TF_WORKING_DIR }}
          framework: terraform
          soft_fail: false

      - name: Terraform Plan
        run: |
          terraform plan \
          -input=false \
          -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan
